refactor to pass shellcheck

diff --git a/playlist b/playlist
--- a/playlist
+++ b/playlist
@@ -1,56 +1,27 @@
 #!/usr/bin/env bash
+
 set -e
 
-source ~/.bsl/bsl.bash
-source ~/.bsl/flags.bash
+#source ~/.bsl/bsl.bash
 
-trap cleanup SIGINT EXIT
+# shellcheck disable=2034
+bsl_CYAN="\033[1;96m"
+bsl_RED="\033[0;91m"
+# shellcheck disable=2034
+bsl_CYAN="\033[1;96m"
+# shellcheck disable=2034
+bsl_GREEN="\033[0;92m"
+bsl_RESET='\033[0m'
 
-EXTENSIONS=(
-    3gp
-    asf
-    avi
-    flv
-    m2ts
-    m4a
-    m4v
-    mkv
-    mov
-    mp3
-    mp4
-    mpg
-    mts
-    nsc
-    nsv
-    nut
-    ra
-    ram
-    rm
-    rv
-    ts
-    ty
-    webm
-    wmv
-)
+bsl_die() {
+    echo -e "${bsl_RED}ERROR:${bsl_RESET}" "$@" >&2
+    exit 1
+}
 
-# bitfields
-WATCHED=1
-YT_ID=2
-MD5_ID=4
 
-WORK_DIR="$(pwd)"
-IS_MAC=
-RATE='1.0'
-PLAYER_PID=0
-INDEX_PREFIX_REGEX='(^[0-9]{3})[[:space:]]-[[:space:]](.*)$'
-# (index) - [(yt id)] (file name)
-INDEX_PREFIX_REGEX_V2='(^[0-9]{3})[[:space:]]-[[:space:]]\[([-\_A-za-z0-9]{11})\](.*)$'
-declare -r INDEX_PREFIX_REGEX_V3='(^[0-9]+)[[:space:]]([0-9A-F]{2})[[:space:]]\[([-\_A-za-z0-9]{11})\](.*)$'
-declare -r INDEX_V3=1
-declare -r BITMASK_V3=2
-declare -r ID_V3=3
-declare -r NAME_V3=4
-
+bsl_panic() {
+    bsl_die "$@"
+}
 
 preflight() {
     if [[ ! $(which vlc) ]]; then
@@ -59,15 +30,60 @@ preflight() {
         exit 1
     fi
 
-    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-        # ...
-        IS_MAC=0
-        # TODO make stat,sed,date,etc. functions to make this work cross platform
-    elif [[ "$OSTYPE" == "darwin"* ]]; then
-        # Mac OSX
-        IS_MAC=1
-    fi
+    #if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+    #    # ...
+    #    IS_MAC=0
+    #    # TODO make stat,sed,date,etc. functions to make this work cross platform
+    #elif [[ "$OSTYPE" == "darwin"* ]]; then
+    #    # Mac OSX
+    #    IS_MAC=1
+    #fi
 
+	trap cleanup SIGINT EXIT
+
+	declare -gra EXTENSIONS=(
+		3gp
+		asf
+		avi
+		flv
+		m2ts
+		m4a
+		m4v
+		mkv
+		mov
+		mp3
+		mp4
+		mpg
+		mts
+		nsc
+		nsv
+		nut
+		ra
+		ram
+		rm
+		rv
+		ts
+		ty
+		webm
+		wmv
+	)
+
+	# bitfields
+	declare -gr WATCHED=1
+
+	declare -gr WORK_DIR="$PWD"
+	#IS_MAC=
+	declare -g RATE='1.0'
+	declare -g PLAYER_PID=0
+	# shellcheck disable=2034
+	declare -gr INDEX_PREFIX_REGEX='(^[0-9]{3})[[:space:]]-[[:space:]](.*)$'
+	# (index) - [(yt id)] (file name)
+	declare -gr INDEX_PREFIX_REGEX_V2='(^[0-9]{3})[[:space:]]-[[:space:]]\[([-\_A-za-z0-9]{11})\](.*)$'
+	declare -gr INDEX_PREFIX_REGEX_V3='(^[0-9]+)[[:space:]]([0-9A-F]{2})[[:space:]]\[([-\_A-za-z0-9]{11})\](.*)$'
+	declare -gr INDEX_V3=1
+	declare -gr BITMASK_V3=2
+	declare -gr ID_V3=3
+	declare -gr NAME_V3=4
 }
 
 cleanup() {
@@ -80,15 +96,16 @@ cleanup() {
 is_indexed() { [[ "$1" =~ $INDEX_PREFIX_REGEX_V3 ]]; }
 
 is_playable() {
-    local name="$(basename "$1")"
+    local name
+    name="$(basename "$1")" || bsl_die
     local extention="${name##*.}"
-    [[ "${EXTENSIONS[*]}" =~ "$extention" ]]
+    [[ "${EXTENSIONS[*]}" =~ $extention ]]
 }
 
 is_watched() {
     local video=$1
     if [[ "$video" =~ $INDEX_PREFIX_REGEX_V3 ]]; then
-        [[ 1 == $(( ${BASH_REMATCH[BITMASK_V3]} & WATCHED )) ]]
+        [[ 1 == $(( BASH_REMATCH[BITMASK_V3] & WATCHED )) ]]
     fi
 }
 
@@ -109,15 +126,13 @@ mark_watched() {
     first=$((first - 1))
     last=$((last - 1))
     if ! [[ 0 -le $first && $first -le $last && $last -lt $playlist_len ]]; then
-        echo "len" $playlist_len
-        echo "first" $first
-        echo "last" $last
         bsl_panic "Out of range"
     fi
     if [[ $first -le $last ]]; then
-        for i in `seq $first $last`; do
+        for i in $(seq $first $last); do
             if [[ "${playlist[i]}" =~ $INDEX_PREFIX_REGEX_V3 ]]; then
-                local b=$(printf "%02X" $(( ${BASH_REMATCH[BITMASK_V3]} | WATCHED )) )
+                local b
+                b=$(printf "%02X" $(( BASH_REMATCH[BITMASK_V3] | WATCHED )) ) || bsl_die
                 mv "${playlist[i]}" \
                     "${BASH_REMATCH[INDEX_V3]} $b [${BASH_REMATCH[ID_V3]}]${BASH_REMATCH[NAME_V3]}"
             fi
@@ -143,15 +158,13 @@ unmark_watched() {
     first=$((first - 1))
     last=$((last - 1))
     if ! [[ 0 -le $first && $first -le $last && $last -lt $playlist_len ]]; then
-        echo "len" $playlist_len
-        echo "first" $first
-        echo "last" $last
         bsl_panic "Out of range"
     fi
     if [[ $first -le $last ]]; then
-        for i in `seq $first $last`; do
+        for i in $(seq $first $last); do
             if [[ "${playlist[i]}" =~ $INDEX_PREFIX_REGEX_V3 ]]; then
-                local b=$(printf "%02X" $(( ${BASH_REMATCH[BITMASK_V3]} & ~WATCHED )) )
+                local b
+                b=$(printf "%02X" $(( BASH_REMATCH[BITMASK_V3] & ~WATCHED )) ) || bsl_die
                 mv "${playlist[i]}" \
                     "${BASH_REMATCH[INDEX_V3]} $b [${BASH_REMATCH[ID_V3]}]${BASH_REMATCH[NAME_V3]}"
             fi
@@ -172,16 +185,22 @@ play() {
             PLAYER_PID=$!
             local prev_time=0
             sleep 1
-            local stats="$(curl -s -u :1234 http://127.0.0.1:8080/requests/status.xml)"
-            local length="$(sed -n 's@.*<length>\(.*\)</length>.*@\1@p' <<< "$stats")"
+            local stats
+            stats="$(curl -s -u :1234 http://127.0.0.1:8080/requests/status.xml)" || bsl_die
+            stats="$(curl -s -u :1234 http://127.0.0.1:8080/requests/status.xml)" || bsl_die
+            local length
+            length="$(sed -n 's@.*<length>\(.*\)</length>.*@\1@p' <<< "$stats")" || bsl_die
             while true; do
                 sleep 1
                 stats="$(curl -s -u :1234 http://127.0.0.1:8080/requests/status.xml)"
-                local state="$(sed -n 's@.*<state>\(.*\)</state>.*@\1@p' <<< "$stats")"
-                local time="$(sed -n 's@.*<time>\(.*\)</time>.*@\1@p' <<< "$stats")"
-                if [[ $(($length - $time)) -le 60 && $marked == 0 ]]; then
-                    if [[ "$video" =~ $INDEX_PREFIX_REGEX_V3 ]]; then
-                        mark_watched ${BASH_REMATCH[INDEX_V3]}
+                local state
+                state="$(sed -n 's@.*<state>\(.*\)</state>.*@\1@p' <<< "$stats")" || bsl_die
+				local time
+                time="$(sed -n 's@.*<time>\(.*\)</time>.*@\1@p' <<< "$stats")" || bsl_die
+                if [[ $((length - time)) -le 60 && $marked == 0 ]]; then
+                    if [[ $video =~ $INDEX_PREFIX_REGEX_V3 ]]; then
+                        local n=$(( 10#${BASH_REMATCH[INDEX_V3]} ))
+                        mark_watched $n
                         marked=1
                     fi
                 fi
@@ -223,36 +242,6 @@ playlist_print() {
     done
 }
 
-#find_missing() {
-#    # --no-download --write-playlist-metafiles
-#    local folder="${1:-$WORK_DIR}"
-#    local playlist=()
-#    load_indexed_files playlist
-#
-#    local indexes=()
-#    for i in "${playlist[@]}"; do
-#        if [[ "$i" =~ $INDEX_PREFIX_REGEX ]]; then
-#            indexes+=( "$(echo ${BASH_REMATCH[1]%%-*} | bc)" )
-#            #echo "indexes" "$(echo ${BASH_REMATCH[1]%%-*} | bc)"
-#        fi
-#    done
-#
-#    if [[ 0 -eq ${#indexes[@]} ]]; then
-#        bsl_panic "No playlist files.";
-#    fi
-#
-#    local result=()
-#    local indexes_len=${#indexes[@]}
-#        for ((i=1;i<=${indexes[-1]};++i)); do
-#            local tmp=$(bsl_binary_search_int indexes 0 $indexes_len "$i")
-#            if [[ $tmp == $indexes_len ]]; then
-#                result+=( "$i" )
-#            fi
-#        done
-#        sed 's/ /,/g' <<< ${result[@]}
-#
-#    }
-
 load_files() {
     # loads video files into array reference
     local -n array_load_files=$1
@@ -269,33 +258,26 @@ load_indexed_files() {
     local -n array_load_indexed_files=$1
     local d="${2:-$WORK_DIR}"
     for i in "$d/"*; do
-        local j="$(basename "$i")"
+        local j
+        j="$(basename "$i")" || bsl_die
         if is_playable "$j" && is_indexed "$j"; then
             array_load_indexed_files+=( "$(basename "$j")" )
         fi
     done
 }
 
-#strip_index_prefix() {
-#    local i="$1"
-#    if [[ "${i}" =~ $INDEX_PREFIX_REGEX_V3 ]]; then
-#        echo "${BASH_REMATCH[INDEX_V3]}"
-#    fi
-#}
-
 reconsile_index_prefixs() {
     local -n array_reconsile_index=$1
 
     for i in "${!array_reconsile_index[@]}"; do
         if [[ "${array_reconsile_index[i]}" =~ $INDEX_PREFIX_REGEX_V3 ]]; then
-            if [[ "${BASH_REMATCH[INDEX_V3]}" != "$(bsl_left_pad $((1+${i})) 3)" ]]; then
+            if [[ "${BASH_REMATCH[INDEX_V3]}" != "$(bsl_left_pad $((1 + i)) 3)" ]]; then
                 mv "${array_reconsile_index[i]}" \
-                    "$(bsl_left_pad $((1+${i})) 3) ${BASH_REMATCH[BITMASK_V3]} [${BASH_REMATCH[ID_V3]}]${BASH_REMATCH[NAME_V3]}"
+                    "$(bsl_left_pad $((1 + i)) 3) ${BASH_REMATCH[BITMASK_V3]} [${BASH_REMATCH[ID_V3]}]${BASH_REMATCH[NAME_V3]}"
             fi
         fi
     done
 }
-
 
 move_item() {
     if [[ -z "$1" || -z "$2" ]]; then bsl_panic "needs two numbers"; fi
@@ -309,11 +291,19 @@ move_item() {
         first=${BASH_REMATCH[1]}
         last=${BASH_REMATCH[2]}
     fi
-    first=$(($first - 1))
+    first=$((first - 1))
     if [[ $to -lt $first ]]; then
-        to=$(($to - 1))
+        to=$((to - 1))
     fi
-    bsl_slide playlist $first $last $to
+    bsl_slide playlist "$first" "$last" "$to"
+    reconsile_index_prefixs playlist
+}
+
+reverse() {
+    local playlist=()
+    load_indexed_files playlist
+    local playlist_len=${#playlist[@]}
+    bsl_reverse playlist 0 "$playlist_len"
     reconsile_index_prefixs playlist
 }
 
@@ -327,13 +317,13 @@ make_playlist() {
 
         if [[ "${playlist[i]}" =~ $INDEX_PREFIX_REGEX_V2 ]]; then
             mv "${playlist[i]}" \
-                "$(bsl_left_pad $((1+${i})) 3) 00 [${BASH_REMATCH[2]}]${BASH_REMATCH[3]}"
+                "$(bsl_left_pad $((1 + i)) 3) 00 [${BASH_REMATCH[2]}]${BASH_REMATCH[3]}"
         elif [[ "${playlist[i]}" =~ $malformed_prefix_regex(.*)$ ]]; then
             mv "${playlist[i]}" \
-                "$(bsl_left_pad $((1+${i})) 3) 00 [00000000000] ${BASH_REMATCH[2]}"
+                "$(bsl_left_pad $((1 + i)) 3) 00 [00000000000] ${BASH_REMATCH[2]}"
         else
             mv "${playlist[i]}" \
-                "$(bsl_left_pad $((1+${i})) 3) 00 [00000000000] ${playlist[i]}"
+                "$(bsl_left_pad $((1 + i)) 3) 00 [00000000000] ${playlist[i]}"
             #"$(bsl_left_pad ${BASH_REMATCH[1]} 3) - ${BASH_REMATCH[2]}"
         fi
     done
@@ -349,17 +339,17 @@ help_parse() {
     local line
     local start
     while read -r line; do
-        if [[ "#START_HELP" == $line ]]; then
+        if [[ "#START_HELP" == "$line" ]]; then
            start=1
         fi
-        if [[ "#END_HELP" == $line ]]; then
+        if [[ "#END_HELP" == "$line" ]]; then
            break
         fi
         if [[ 1 -ne $start ]]; then
             continue
         fi
         if [[ "$line" =~ (^.+\) \#) ]]; then
-            echo -e "  " "$(sed -E 's/#/\t/; s/\)//; s/\|/,/g'  <<< $line)"
+            echo -e "  " "$(sed -E 's/#/\t/; s/\)//; s/\|/,/g'  <<< "$line")"
         fi
     done < "$1"
 }
@@ -369,25 +359,32 @@ download() {
 
     [[ -s "./PLAYLIST_DOWNLOAD_LINK" ]] || bsl_die "Playlist link cannot be found."
 
-    local link="$(cat "./PLAYLIST_DOWNLOAD_LINK")"
+    local link
+    link="$(cat "./PLAYLIST_DOWNLOAD_LINK")" || bsl_die
 
-    local yt_json="$(yt-dlp --flat-playlist --skip-download --dump-json --cookies-from-browser firefox "$link" | jq -s '.')"
-    local yt_json_len=$(jq 'length' <<< "$yt_json")
+    local yt_json
+	# shellcheck disable=2155
+    local yt_json="$(yt-dlp --flat-playlist --skip-download --dump-json --cookies-from-browser firefox "$link" | jq -s '.')" || bsl_die
+    local yt_json_len
+    yt_json_len=$(jq 'length' <<< "$yt_json") || bsl_die
 
     local playlist=()
     load_indexed_files playlist
     local playlist_len=${#playlist[@]}
 
         local missing
-        for ((i = 0; i < $yt_json_len; ++i)); do
-            local yt_title="$(jq -r ".[$i] | .title" <<< "$yt_json")"
-            local yt_id="$(jq -r ".[$i] | .id" <<< "$yt_json")"
-            local yt_index="$(jq -r ".[$i] | .playlist_index" <<< "$yt_json")"
+        for ((i = 0; i < yt_json_len; ++i)); do
+            #local yt_title
+            #yt_title="$(jq -r ".[$i] | .title" <<< "$yt_json")" || bsl_die
+            local yt_id
+            yt_id="$(jq -r ".[$i] | .id" <<< "$yt_json")" || bsl_die
+            local yt_index
+            yt_index="$(jq -r ".[$i] | .playlist_index" <<< "$yt_json")" || bsl_die
             local j=0
             local matched=0
             while ((j < playlist_len)); do
                 if [[ ${playlist[j]} =~ $INDEX_PREFIX_REGEX_V3 ]]; then
-                    if [[ $yt_id == ${BASH_REMATCH[ID_V3]} ]]; then
+                    if [[ "$yt_id" == "${BASH_REMATCH[ID_V3]}" ]]; then
                         ((++matched))
                     fi
                 fi
@@ -399,14 +396,16 @@ download() {
             fi
         done
 
-        bsl_is_null "$missing" && bsl_die "No missing found."
+        bsl_is_empty "$missing" && bsl_die "No missing found."
 
         # strip initial comma
         items="-I ${missing:1}";
-
-        yt-dlp                                                             \
+		# shellcheck disable=2086
+		yt-dlp                                                             \
             --cookies-from-browser firefox                                 \
-            -f "best" --no-part                                            \
+            --embed-chapters                                               \
+            --remote-components ejs:github                                 \
+            -f "bestvideo+bestaudio/best"                                  \
             $items -o "%(playlist_index)03d 00 [%(id)s] %(title)s.%(ext)s" \
             "$link"
     #PLAYER_PID=$!
@@ -454,6 +453,9 @@ main() {
         move) # move item by index $1 to index $2 optionally move range e.g. 3-4 7
             shift
             move_item "$@"
+            ;;
+        reverse) # reverse playlist
+            reverse
             ;;
         help|h|--help|-h) # Shows this help page.
             help_parse "$0"
